# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AltaContribuyente.ui',
# licensing of 'AltaContribuyente.ui' applies.
#
# Created: Thu Feb 18 23:54:54 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(353, 441)
        MainWindow.setMaximumSize(QtCore.QSize(353, 441))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem = QtWidgets.QSpacerItem(97, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.rfc = QtWidgets.QLineEdit(self.centralwidget)
        self.rfc.setMinimumSize(QtCore.QSize(319, 20))
        self.rfc.setReadOnly(False)
        self.rfc.setObjectName("rfc")
        self.gridLayout_7.addWidget(self.rfc, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_7, 1, 0, 1, 3)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.razon = QtWidgets.QLineEdit(self.centralwidget)
        self.razon.setMinimumSize(QtCore.QSize(319, 20))
        self.razon.setReadOnly(False)
        self.razon.setObjectName("razon")
        self.gridLayout_9.addWidget(self.razon, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_9, 2, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        self.bcertificado = QtWidgets.QPushButton(self.centralwidget)
        self.bcertificado.setMinimumSize(QtCore.QSize(75, 23))
        self.bcertificado.setObjectName("bcertificado")
        self.gridLayout.addWidget(self.bcertificado, 0, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.certificado = QtWidgets.QLineEdit(self.centralwidget)
        self.certificado.setMinimumSize(QtCore.QSize(319, 20))
        self.certificado.setReadOnly(True)
        self.certificado.setObjectName("certificado")
        self.gridLayout_2.addWidget(self.certificado, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_2, 3, 0, 1, 3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 1, 1, 1)
        self.bllave = QtWidgets.QPushButton(self.centralwidget)
        self.bllave.setObjectName("bllave")
        self.gridLayout_3.addWidget(self.bllave, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.llave = QtWidgets.QLineEdit(self.centralwidget)
        self.llave.setMinimumSize(QtCore.QSize(319, 20))
        self.llave.setReadOnly(True)
        self.llave.setObjectName("llave")
        self.gridLayout_4.addWidget(self.llave, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_4, 4, 0, 1, 3)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.contrasena = QtWidgets.QLineEdit(self.centralwidget)
        self.contrasena.setMinimumSize(QtCore.QSize(319, 20))
        self.contrasena.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.contrasena.setObjectName("contrasena")
        self.gridLayout_6.addWidget(self.contrasena, 1, 0, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_6, 5, 0, 1, 3)
        self.guardar = QtWidgets.QPushButton(self.centralwidget)
        self.guardar.setObjectName("guardar")
        self.gridLayout_11.addWidget(self.guardar, 6, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 353, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Alta Contribuyente", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Agrega cretificado y llave", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "RFC", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("MainWindow", "Razon Social", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "Archivo .cer", None, -1))
        self.bcertificado.setText(QtWidgets.QApplication.translate("MainWindow", "Certificado", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Archivo .key", None, -1))
        self.bllave.setText(QtWidgets.QApplication.translate("MainWindow", "Llave", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Contraseña", None, -1))
        self.guardar.setText(QtWidgets.QApplication.translate("MainWindow", "Guardar", None, -1))

