# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CFDIMasivo.ui',
# licensing of 'CFDIMasivo.ui' applies.
#
# Created: Thu Feb 18 23:54:53 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(807, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(391, 121))
        self.groupBox.setObjectName("groupBox")
        self.bfechaInicial = QtWidgets.QPushButton(self.groupBox)
        self.bfechaInicial.setGeometry(QtCore.QRect(40, 30, 111, 23))
        self.bfechaInicial.setObjectName("bfechaInicial")
        self.bfechaFinal = QtWidgets.QPushButton(self.groupBox)
        self.bfechaFinal.setGeometry(QtCore.QRect(240, 30, 111, 23))
        self.bfechaFinal.setObjectName("bfechaFinal")
        self.lfechaInicial = QtWidgets.QLineEdit(self.groupBox)
        self.lfechaInicial.setGeometry(QtCore.QRect(40, 60, 113, 20))
        self.lfechaInicial.setObjectName("lfechaInicial")
        self.lfechaFinal = QtWidgets.QLineEdit(self.groupBox)
        self.lfechaFinal.setGeometry(QtCore.QRect(240, 60, 113, 20))
        self.lfechaFinal.setObjectName("lfechaFinal")
        self.bdescarga = QtWidgets.QPushButton(self.groupBox)
        self.bdescarga.setGeometry(QtCore.QRect(160, 90, 75, 23))
        self.bdescarga.setObjectName("bdescarga")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(362, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.bexportar = QtWidgets.QPushButton(self.groupBox_2)
        self.bexportar.setGeometry(QtCore.QRect(140, 90, 75, 23))
        self.bexportar.setObjectName("bexportar")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 16))
        self.label_2.setObjectName("label_2")
        self.lrazon = QtWidgets.QLabel(self.groupBox_2)
        self.lrazon.setGeometry(QtCore.QRect(20, 30, 311, 16))
        self.lrazon.setMinimumSize(QtCore.QSize(311, 16))
        self.lrazon.setText("")
        self.lrazon.setObjectName("lrazon")
        self.lrfc = QtWidgets.QLabel(self.groupBox_2)
        self.lrfc.setGeometry(QtCore.QRect(20, 70, 311, 16))
        self.lrfc.setText("")
        self.lrfc.setObjectName("lrfc")
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(101, 16))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(235, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.lRfcRazon = QtWidgets.QLineEdit(self.centralwidget)
        self.lRfcRazon.setMinimumSize(QtCore.QSize(301, 20))
        self.lRfcRazon.setObjectName("lRfcRazon")
        self.gridLayout.addWidget(self.lRfcRazon, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.tCfdi = QtWidgets.QTableView(self.centralwidget)
        self.tCfdi.setMinimumSize(QtCore.QSize(781, 301))
        self.tCfdi.setObjectName("tCfdi")
        self.gridLayout.addWidget(self.tCfdi, 3, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 807, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuEdicion = QtWidgets.QMenu(self.menubar)
        self.menuEdicion.setObjectName("menuEdicion")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDescarga = QtWidgets.QAction(MainWindow)
        self.actionDescarga.setObjectName("actionDescarga")
        self.actionAgrega = QtWidgets.QAction(MainWindow)
        self.actionAgrega.setObjectName("actionAgrega")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionExportar = QtWidgets.QAction(MainWindow)
        self.actionExportar.setObjectName("actionExportar")
        self.actionVer_PDF = QtWidgets.QAction(MainWindow)
        self.actionVer_PDF.setObjectName("actionVer_PDF")
        self.menuArchivo.addAction(self.actionDescarga)
        self.menuArchivo.addAction(self.actionAgrega)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuEdicion.addAction(self.actionExportar)
        self.menuEdicion.addAction(self.actionVer_PDF)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEdicion.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Periodo", None, -1))
        self.bfechaInicial.setText(QtWidgets.QApplication.translate("MainWindow", "Fecha Inicial", None, -1))
        self.bfechaFinal.setText(QtWidgets.QApplication.translate("MainWindow", "Fecha Final", None, -1))
        self.lfechaInicial.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "AAAA-MM-dd", None, -1))
        self.lfechaFinal.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "AAAA-MM-dd", None, -1))
        self.bdescarga.setText(QtWidgets.QApplication.translate("MainWindow", "Descarga", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Contribuyente", None, -1))
        self.bexportar.setText(QtWidgets.QApplication.translate("MainWindow", "Exportar XLS", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Razón Social:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "RFC", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Filtrar Razón", None, -1))
        self.menuArchivo.setTitle(QtWidgets.QApplication.translate("MainWindow", "Archivo", None, -1))
        self.menuEdicion.setTitle(QtWidgets.QApplication.translate("MainWindow", "Edicion", None, -1))
        self.actionDescarga.setText(QtWidgets.QApplication.translate("MainWindow", "Descarga", None, -1))
        self.actionAgrega.setText(QtWidgets.QApplication.translate("MainWindow", "Agrega", None, -1))
        self.actionSalir.setText(QtWidgets.QApplication.translate("MainWindow", "Salir", None, -1))
        self.actionExportar.setText(QtWidgets.QApplication.translate("MainWindow", "Exportar", None, -1))
        self.actionVer_PDF.setText(QtWidgets.QApplication.translate("MainWindow", "Ver PDF", None, -1))

